[package]
name = "growth-ring"
version = "0.1.0"
authors = ["Determinant <tederminant@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "1.8.1"
lru = "0.5.1"

[lib]
name = "growthring"
path = "src/lib.rs"
crate-type = ["dylib", "rlib", "staticlib"]


[profile.release]
lto = true
debug = true
