[package]
name = "growth-ring"
version = "0.1.0"
authors = ["Determinant <tederminant@gmail.com>"]
edition = "2018"
homepage = "https://github.com/Determinant/growth-ring"
keywords = ["wal", "db", "futures"]
license = "MIT"
description = "Simple and modular write-ahead-logging implementation."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "1.8.1"
lru = "0.5.1"
scan_fmt = "0.2.5"
regex = "1"
async-trait = "0.1"
futures = "0.3"
libaio-futures = "0.1.1"
nix = "0.17.0"
libc = "0.2.71"

[dev-dependencies]
hex = "0.4.2"
rand = "0.7.3"
indexmap = "1.4.0"

[lib]
name = "growthring"
path = "src/lib.rs"
crate-type = ["dylib", "rlib", "staticlib"]


[profile.release]
lto = true
debug = true
