[package]
name = "growth-ring"
version = "0.1.0"
authors = ["Determinant <tederminant@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "1.8.1"
lru = "0.5.1"
scan_fmt = "0.2.5"
regex = "1"
async-trait = "0.1"

[dev-dependencies]
hex = "0.4.2"
libc = "0.2.44"
nix = "0.17.0"
rand = "0.7.3"
indexmap = "1.4.0"
futures = "0.3"

[lib]
name = "growthring"
path = "src/lib.rs"
crate-type = ["dylib", "rlib", "staticlib"]


[profile.release]
lto = true
debug = true
